version: "3.8"

services:
  backend:
    image: motelregistry.azurecr.io/backend:latest
    container_name: drf_backend_prod
    expose:
      - "8000"
    env_file:
      - .env.prod
    command: gunicorn --bind 0.0.0.0:8000 app.wsgi:application

  frontend:
    image: motelregistry.azurecr.io/frontend:latest
    container_name: react_frontend_prod
    expose:
      - "5173"
    depends_on:
      - backend

  nginx:
    image: motelregistry.azurecr.io/nginx-proxy:latest
    container_name: nginx_proxy_prod
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
