version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    volumes:
      - ${WEBAPP_STORAGE_HOME}/postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    image: motelregistry.azurecr.io/backend:latest
    container_name: drf_backend
    volumes:
      - django_static_volume:/app/staticfiles
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=db
    depends_on:
      - db

  frontend:
    image: motelregistry.azurecr.io/frontend:latest
    container_name: react_frontend
    depends_on:
      - backend

  nginx:
    image: motelregistry.azurecr.io/nginx-proxy:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - django_static_volume:/app/staticfiles
    depends_on:
      - backend
      - frontend

volumes:
  django_static_volume:
